repos:
-   repo: https://github.com/pycqa/isort
    rev: 5.13.2  # Use the ref you want to point at
    hooks:
    -   id: isort
-   repo: https://github.com/psf/black
    rev: 23.12.1  # Use the ref you want to point at
    hooks:
    - id: black
      language_version: python3.10  # Should match the python version you're using
