name: Docker Image CI

on:
  pull_request:
    branches: [ "main" ]

env:
  IMAGE_NAME: cvfe
  GHCR_REGISTRY: ghcr.io/nikronic
  DOCKERFILE: Dockerfile
  
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Get package version
      run: |
        VER=$(cat VERSION)
        echo "VERSION=$VER" >> $GITHUB_ENV
    - name: Login to GHCR
      run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ${{ env.IMAGE_NAME }}:${{ env.VERSION }}
    - name: Tag the image with GHCR
      run: docker tag ${{ env.IMAGE_NAME }}:${{ env.VERSION }} ${{ env.GHCR_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.VERSION }}
    - name: Publish image to Github
      run: docker push ${{ env.GHCR_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.VERSION }}
