name: SDK Test

on:
  push:
  pull_request:
    branches: [ "main" ]
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Update pip
      run: python -m pip install --upgrade pip
    - name: Build the package
      run: pip install .[test]
    - name: Run the tests
      run: pytest
